//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeSourcebook.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeSourcebook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на userdata/userConnectionData.xml.
        /// </summary>
        internal static string ConnectionUserDataXMLFile {
            get {
                return ResourceManager.GetString("ConnectionUserDataXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL queries/PostgreSQL/CreateTables.sql.
        /// </summary>
        internal static string NpsqlDbCreationCmdFile {
            get {
                return ResourceManager.GetString("NpsqlDbCreationCmdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL queries/PostgreSQL/InsertDummy.sql.
        /// </summary>
        internal static string NpsqlInsertDummyRecordsCmdFile {
            get {
                return ResourceManager.GetString("NpsqlInsertDummyRecordsCmdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL queries/PostgreSQL/TablesList.sql.
        /// </summary>
        internal static string NpsqlListTablesCmdFile {
            get {
                return ResourceManager.GetString("NpsqlListTablesCmdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResetImage {
            get {
                object obj = ResourceManager.GetObject("ResetImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на userdata/userSettingsData.xml.
        /// </summary>
        internal static string SettingsUserDataXMLFile {
            get {
                return ResourceManager.GetString("SettingsUserDataXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL queries/SQLite/CreateTables.sql.
        /// </summary>
        internal static string SqliteDbCreationCmdFile {
            get {
                return ResourceManager.GetString("SqliteDbCreationCmdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQLite/EmployeesSourcebook.db.
        /// </summary>
        internal static string SqliteDbFile {
            get {
                return ResourceManager.GetString("SqliteDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL queries/SQLite/InsertDummy.sql.
        /// </summary>
        internal static string SqliteInsertDummyRecordsCmdFile {
            get {
                return ResourceManager.GetString("SqliteInsertDummyRecordsCmdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL queries/SQLite/TablesList.sql.
        /// </summary>
        internal static string SqliteListTablesCmdFile {
            get {
                return ResourceManager.GetString("SqliteListTablesCmdFile", resourceCulture);
            }
        }
    }
}
